language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then
  -   sudo apt-get update -qq
  -   sudo apt-get install -y -qq mingw-w64
  - fi

script:
  make -C build/gmake.linux   clean all
  make -C build/gmake.windows clean all CC=i686-w64-mingw32-gcc

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx

osx_image:
  xcode61
