language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
      env: OS=linux
    - compiler: clang
      os: osx
      env: OS=darwin

script:
  make -C build/gmake.x$OS clean all

branches:
  only:
    - master

notifications:
  email: false

osx_image:
  xcode61
