language: cpp

compiler:
  - gcc
  - clang

before_install:

script:
  make -C build/gmake.linux clean all

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx

osx_image:
  xcode61
